# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target wasm32-unknown-unknown --release --verbose
      - name: Create Dist folder
        run: mkdir dist
      - name: Move js file to dist
        run: cp ./js ./dist -r
      - name: Move resource folder
        run: cp ./resources ./dist -r
      - name: Move index.html
        run: cp ./index.html ./dist
      - name: Move wasm file to dist
        run: cp -R target/wasm32-unknown-unknown/release/*.wasm ./dist
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: "Web Artifact"
          path: ./dist
